version: "3"

volumes:
  registry:

services:
  registry:
    image: "registry:2"
    container_name: "registry"
    restart: "always"
    ports:
      - "5000:5000"
    volumes:
      - "registry:/var/lib/registry"
    environment:
      - "REGISTRY_STORAGE_DELETE_ENABLED=true"
